/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\common\MotionProfiles.cpp
 *  model: ModelControl
 *  expmt: ModelControl
 *  date:  October 26, 2011
 *  time:  1:27:39 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

