/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  include\common\MotionProfiles.h
 *  model: RCCMotionStack
 *  expmt: RCCMotionStack
 *  date:  November 17, 2011
 *  time:  12:16:29 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
