/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  include\common\MotionProfiles.h
 *  model: ModelControl
 *  expmt: ModelControl
 *  date:  November 1, 2011
 *  time:  10:48:24 am
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
