/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  include\common\MotionProfiles.h
 *  model: gravity_test_vA
 *  expmt: gravity_test_vA
 *  date:  October 7, 2011
 *  time:  5:35:40 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
