time stamp

# event name                        | type  |
#-----------------------------------+-------|
# jntX.e_OVERCURRENT_<bool>         | edge  |
# jntX.e_UNDERVOLTAGE_<bool>        | edge  |
# jntX.e_OVERVOLTAGE_<bool>         | edge  |
# jntX.e_OVERTEMP_<bool>            | edge  |
# jntX.e_HALL_ERR                   | level |
# jntX.e_ENCODER_ERR                | level |
# jntX.e_SINE_COMM_INIT_ERR         | level |
# jntX.e_EMERGENCY_STOP             | level |
# jntX.e_EC_TIMEOUT                 | level |
# jntX.e_EC_CONN_LOST_<bool>        | edge  |
# jntX.e_I2T_EXCEEDED_<bool>        | edge  |
string driver_event
