/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\common\MotionProfiles.cpp
 *  model: RCCMotionStack
 *  expmt: RCCMotionStack
 *  date:  November 17, 2011
 *  time:  7:24:58 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

