/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\common\MotionProfiles.cpp
 *  model: RCCMotionStack
 *  expmt: RCCMotionStack
 *  date:  December 8, 2011
 *  time:  5:45:50 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

